package sep.project;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author harald
 */
public class GUIRecruitmentForm extends javax.swing.JFrame {

    /**
     * Creates new form GUIRecruitmentForm
     */
    public GUIRecruitmentForm(String user) {
        initComponents();
        setUserButton(user);
    }
    
        public void setUserButton(String user) {
        switch (user) {
            case "ProductionManager": {
                productionButton.setSelected(true);
                sender = "ProductionManager";
                break;
            }
            case "ServiceManager": {
                serviceButton.setSelected(true);
                sender = "ServiceManager";
                break;
            }
            case "AdminManager": {
                adminButton.setSelected(true);
                sender = "AdministrationManager";
                break;
            }
            case "FinancialManager": {
                financialButton.setSelected(true);
                sender = "FinancialManager";
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contractButtonGroup = new javax.swing.ButtonGroup();
        departmentButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        contractTypeLabel = new javax.swing.JLabel();
        fullTimeButton = new javax.swing.JRadioButton();
        partTimeButton = new javax.swing.JRadioButton();
        buttonGroupTitle = new javax.swing.JLabel();
        adminButton = new javax.swing.JRadioButton();
        serviceButton = new javax.swing.JRadioButton();
        productionButton = new javax.swing.JRadioButton();
        financialButton = new javax.swing.JRadioButton();
        experienceLabel = new javax.swing.JLabel();
        experience = new javax.swing.JTextField();
        jobTitleLabel = new javax.swing.JLabel();
        jobTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Recruitment Request");

        contractTypeLabel.setText("Contract type:");

        contractButtonGroup.add(fullTimeButton);
        fullTimeButton.setText("Full time");
        fullTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeButtonActionPerformed(evt);
            }
        });

        contractButtonGroup.add(partTimeButton);
        partTimeButton.setText("Part time");
        partTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeButtonActionPerformed(evt);
            }
        });

        buttonGroupTitle.setText("Requesting department");

        departmentButtonGroup.add(adminButton);
        adminButton.setText("Administration");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        departmentButtonGroup.add(serviceButton);
        serviceButton.setText("Services");
        serviceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceButtonActionPerformed(evt);
            }
        });

        departmentButtonGroup.add(productionButton);
        productionButton.setText("Production");
        productionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productionButtonActionPerformed(evt);
            }
        });

        departmentButtonGroup.add(financialButton);
        financialButton.setText("Financial");
        financialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financialButtonActionPerformed(evt);
            }
        });

        experienceLabel.setText("Years of experience:");

        jobTitleLabel.setText("Job title:");

        jLabel2.setText("Job description:");

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        submitButton.setBackground(new java.awt.Color(51, 255, 51));
        submitButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(0, 0, 0));
        submitButton.setText("Submit");
        submitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonGroupTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(contractTypeLabel)
                                .addGap(34, 34, 34)
                                .addComponent(fullTimeButton)
                                .addGap(31, 31, 31)
                                .addComponent(partTimeButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adminButton)
                                .addGap(18, 18, 18)
                                .addComponent(serviceButton)
                                .addGap(9, 9, 9)
                                .addComponent(productionButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(financialButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(experienceLabel)
                                    .addGap(43, 43, 43)
                                    .addComponent(experience, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jobTitleLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(submitButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(70, 70, 70)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contractTypeLabel)
                    .addComponent(fullTimeButton)
                    .addComponent(partTimeButton))
                .addGap(18, 18, 18)
                .addComponent(buttonGroupTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminButton)
                    .addComponent(productionButton)
                    .addComponent(serviceButton)
                    .addComponent(financialButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(experienceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(experience, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jobTitleLabel)
                    .addComponent(jobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String sender = this.sender;
        String receiver = "SeniorHRManager";        
        if (sender.isEmpty() || description.getText().isEmpty() || jobTitle.getText().isEmpty() || experience.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Missing");
        } else {
            RecruitmentForm r = new RecruitmentForm(sender, department, experience.getText().trim(), jobTitle.getText().trim(), description.getText().trim(), contractType);
            try {
                s.sendForm(r);
            } catch (IOException ex) {
                Logger.getLogger(GUIFinancialRequestForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
            JOptionPane.showMessageDialog(null, "Data Submitted");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void financialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financialButtonActionPerformed
        sender = "FinancialManager";
        department = "Financial";
    }//GEN-LAST:event_financialButtonActionPerformed

    private void productionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productionButtonActionPerformed
        sender = "ProductionManager";
        department = "Production";
    }//GEN-LAST:event_productionButtonActionPerformed

    private void serviceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceButtonActionPerformed
        sender = "ServiceManager";
        department = "Services";
    }//GEN-LAST:event_serviceButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        sender = "AdministrationManager";
        department = "Administration";
    }//GEN-LAST:event_adminButtonActionPerformed

    private void partTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeButtonActionPerformed
        contractType = "Part time";
    }//GEN-LAST:event_partTimeButtonActionPerformed

    private void fullTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeButtonActionPerformed
        contractType = "Full time";
    }//GEN-LAST:event_fullTimeButtonActionPerformed

    private final ServerConnector s = new ServerConnector();
    private String department;
    private String sender;
    private String contractType;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminButton;
    private javax.swing.JLabel buttonGroupTitle;
    private javax.swing.ButtonGroup contractButtonGroup;
    private javax.swing.JLabel contractTypeLabel;
    private javax.swing.ButtonGroup departmentButtonGroup;
    private javax.swing.JTextArea description;
    private javax.swing.JTextField experience;
    private javax.swing.JLabel experienceLabel;
    private javax.swing.JRadioButton financialButton;
    private javax.swing.JRadioButton fullTimeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jobTitle;
    private javax.swing.JLabel jobTitleLabel;
    private javax.swing.JRadioButton partTimeButton;
    private javax.swing.JRadioButton productionButton;
    private javax.swing.JRadioButton serviceButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
